### ISSUE TITLE
Build the landing page

### ISSUE THREAD

**Issue by bloodfuse** [bloodfuse/frontend#1]

**Comment by bloodfuse** [comment]
Build the landing page for bloodfuse in accordance with the design

https://www.figma.com/file/9xw9AXLl9R2mrZVEfOcO0d/BloodFuse-Backup?node-id=0%3A1

**Comment by taofeek-ob** [comment]
I will (want to) work on the desktop view of the landing page today, so @frankudoags can work on the mobile responsiveness after I make a pr.

**Comment by frankudoags** [comment]
Completed
